version: '3'

services:
  postgresql:
    image: postgres
    container_name: sagtech-task
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USE=sagtech
      - POSTGRES_PASSWORD=sagtech
      - POSTGRES_DATABASE=sagtech
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-sagtech
    ports:
      - '6379-6379'